roman:
  vars:
    ansible_user: vagrant
  hosts:
    'hepburn.local:2222':
      ansible_ssh_private_key_file: .vagrant/machines/hepburn/virtualbox/private_key
    'peck.local:2200':
      ansible_ssh_private_key_file: .vagrant/machines/peck/virtualbox/private_key
