roman:
  vars:
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3 # Only the venv playbook should use this; other playbooks should switch to the venv that it sets up
  hosts:
    'hepburn.local:2222':
      ansible_ssh_private_key_file: .vagrant/machines/hepburn/virtualbox/private_key
    'peck.local:2200':
      ansible_ssh_private_key_file: .vagrant/machines/peck/virtualbox/private_key
