---
- hosts: roman
  gather_facts: no
  tasks:
    - name: 'Get start time'
      command: date
      register: start_time
    - debug:
        var: start_time.stdout
    - name: 'Long running operation'
      shell: ls MEOW; echo 'hi'; exit 0
      register: async_result
      async: 401
      poll: 1
      retries: 5
      delay: 1
      until: async_result is succeeded
    - debug:
        var: async_result
    - name: 'Get end time'
      command: date
      register: end_time
    - debug:
        var: end_time.stdout
