---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Do it
      shell: |
        ssh-keyscan -H sftp_server >> ~/.ssh/known_hosts
        mkdir -p tmp/stuff
        touch tmp/stuff/1
        touch tmp/stuff/2
        touch tmp/stuff/3
        lftp -c 'open -e "mirror --parallel=20 -R ./tmp/stuff/ /upload/2021" sftp://foo@sftp_server'
      register: output
    - debug:
        var: output.stdout
